### ISSUE TITLE
Better way to create static copy of drupal.cz

### ISSUE THREAD

**Issue by radimklaska** [Drupalcz/old.drupal.cz#1]
Na mini weby normalne pouzivam
```
wget --recursive --page-requisites --html-extension --convert-links --restrict-file-names=windows --waitretry=3 --domains www.drupal.cz https://www.drupal.cz
```
vysledek se ale zda byt neumerne maly a rychly - jeste otestuji.

Naopak 
```
wget -P . -mpck --user-agent="" -e robots=off --wait 1 -E https://www.drupal.cz/
```
(nalezeno zde: https://swsblog.stanford.edu/blog/creating-static-copy-website ) uz bezi druhy den a jsem na 1,5GB - nejsem si jisty jestli mi to github dovoli pushnout.

**Comment by miromichalicka** [comment]
Github to dovoli pushnut, ale nezda sa mi ta velkost, nemyslim si ze mame tolko nodov.

**Comment by radimklaska** [comment]
Oba vysledky jsou tady v brancich, imho to pak "optimalizuje" protoze oba testy jsou kolem 500MB dohromady.
